### ISSUE TITLE
Horizontal Rule is barely visible

### ISSUE THREAD

**Issue by cballenar** [dracula/logseq#25]
The horizontal rule (`---`) is barely visible.

<img width="761" alt="Screenshot 2024-05-27 at 12 49 20 PM" src="https://github.com/dracula/logseq/assets/687315/fd023ea5-a49c-4e01-b525-bfa4f74b6edb">

I'm not sure if this one should be the same as the horizontal rule that divides journals, it's hard to make it less subtle without losing completely again. Plus, it is more slightly narrow than the journal hr.

**Comment by cballenar** [comment]
I'm having a hard time figuring out where it's inheriting its value from.

we've got the following getting applied:

```css
:root {
  --comment: #6272a4;
}
.dark-theme,
html[data-theme="dark"] {
  --ls-border-color: var(--comment);
}
```

Which should change the hr as well as the date border. But both of them actually have a more subtle gray color.

---

Alternatively... we could just patch this applying light or lighter to hr directly:

```
hr {
  border-color: var(--light-background);
}
```
